summary: This example demonstrates using a novel method, Probabilistic Learning on Manifolds (PLoM), to develop surrogate models for structural responses under earthquake ground motion inputs.
difficulty: 0
