summary: This example demonstrates defining multiple models of the structure's behavior, and using multiple options to perform time history analysis to obtain EDPs commonly used in seismic risk analysis.
difficulty: 0
