summary: This page shows two examples on how to incorporate spatial variability into UQ analysis by using various special materials, namely ElasticIsotropic, PM4Sand, and PDMY03, in Site Response option under EVENT tab.
difficulty: 0
