summary: This example considers the problem of uncertainty quantification in a three story shear building where the ground shaking is represented by sythetic ground motion records based on two methods; Vlachos, Papakonstantinou and Deodatis (2018), and Dabaghi and Der Kiureghian (2018).
difficulty: 0
